### ISSUE TITLE
Would angluar shifts from 0 to +pi be sufficient?

### ISSUE THREAD

**Issue by bgobbi** [isayev/ASE_ANI#20]
Thanks fro making this available this is very exciting research!

Ever since reading the papers I have been asking myself if it is really necessary to sample the angular shift from -PI to +PI?
It seems to me that you can not distinguish positive from negative angles and therefore should be able to just sample from 0 to PI. Since you are looking at triples of atoms I see no way to define right hand versus left hand angles.

Could you comment on this?
Thanks,
Alberto

**Comment by Jussmith01** [comment]
Hi Alberto,

The representation in earlier code worked in 0 to Pi but externally -Pi to Pi was passed in. This has since been changed in the newest code (in the 'test_branch' branch) which is currently undergoing tests and will soon be merged into master.

 You can see this in the following parameters file:
https://github.com/isayev/ASE_ANI/blob/test_branch/ani_models/ani-1ccx_8x/rHCNO-5.2R_16-3.5A_a4-8.params'

Best, 
Justin

**Comment by bgobbi** [comment]
Thanks @Jussmith01!
