### ISSUE TITLE
What is 'default_neighborlist' method in aev.py doing?

### ISSUE THREAD

**Issue by yifanyang96** [isayev/ASE_ANI#26]
Hi,

When I was trying to understand your code I got confused about the `default_neighborlist` method. I thought it should select the atoms within the cutoff range but the result is not the case:

<img width="1112" alt="neighborhood_list" src="https://user-images.githubusercontent.com/35789723/54662713-dae1af80-4b19-11e9-9fc6-1e44b80a0719.png">

In this example I set cutoff to 1.1 but species with distance > 1.1 are also included. Could you please explain the method's function or is it implemented incorrectly?

Thanks!

**Comment by zasdfgbnm** [comment]
Hi @yifanyang96, sorry for the late reply, next time please go to https://github.com/aiqm/torchani for TorchANI related issues, because I am not watching this the ASE_ANI repository.  Species with distance > 1.1 are included, this is an expected behavior. The reason for this is basically padding them to the same size so that you could put everything into a tensor of shape (molecule, atom, neighbor). Without doing so, you have to store the list of neighbors of each atom separately, which hurts the performance greatly .

**Comment by zasdfgbnm** [comment]
Also, @yifanyang96 , I have completely rewrote the `AEVComputer`, so the `default_neighborlist` no longer exist...

**Comment by yifanyang96** [comment]
Thanks a lot @zasdfgbnm ! I figured it out soon after I posted this issue.
